site_name: Web estàtica amb mkdocs
nav:
  - Home: /index.html
  - Apartat 01: /apartat01/index.html
  - Apartat 02: /apartat02/index.html
  - Apartat 03: /apartat03/index.html
  - Apartat 04: /apartat04/index.html
  - About: /about/index.html
theme: readthedocs
markdown_extensions: 
  - admonition
docs_dir: 'md'
site_dir: 'docs'