site_name: Web estàtica amb mkdocs
docs_dir: 'md'
site_dir: 'docs'
nav:
  - Home: index.md
  - Apartat 01: Apartat01.md
  - Apartat 02: Apartat02.md
  - Apartat 03: Apartat03.md
  - Apartat 04: Apartat04.md
  - About: about.md
theme: readthedocs
markdown_extensions: 
  - admonition
